/**
 * Auto-generated model catalog.
 *
 * Generated by: @cline/llms/scripts/generate-models.ts
 *
 * WARNING: DO NOT EDIT THIS FILE MANUALLY.
 */
import type { ModelInfo } from "@cline/shared";
/**
 * Model list auto-generated for built-in providers
 * listed in @cline/llms/src/providers/provider-keys.ts
 */
export const GENERATED_PROVIDER_MODELS: {
	version: number;
	providers: Record<string, Record<string, ModelInfo>>;
} = {
	version: 1782923987348,
	providers: {
		aihubmix: {
			"glm-5.2": {
				id: "glm-5.2",
				name: "GLM-5.2",
				contextWindow: 1000000,
				maxInputTokens: 1000000,
				maxTokens: 128000,
				capabilities: [
					"tools",
					"reasoning",
					"structured_output",
					"temperature",
					"prompt-cache",
				],
				pricing: {
					input: 1.1268,
					output: 3.9438,
					cacheRead: 0.2817,
					cacheWrite: 0,
				},
				releaseDate: "2026-06-13",
				family: "glm",
			},
			"qwen3.7-plus": {
				id: "qwen3.7-plus",
				name: "Qwen3.7 Plus",
				contextWindow: 991000,
				maxInputTokens: 991000,
				maxTokens: 64000,
				capabilities: [
					"tools",
					"reasoning",
					"structured_output",
					"temperature",
					"prompt-cache",
				],
				pricing: {
					input: 0.282,
					output: 1.128,
					cacheRead: 0.0564,
					cacheWrite: 0.3525,
				},
				releaseDate: "2026-06-02",
				family: "qwen",
			},
			"qwen3.7-max": {
				id: "qwen3.7-max",
				name: "Qwen3.7 Max",
				contextWindow: 991000,
				maxInputTokens: 991000,
				maxTokens: 64000,
				capabilities: [
					"tools",
					"reasoning",
					"structured_output",
					"temperature",
					"prompt-cache",
				],
				pricing: {
					input: 0.282,
					output: 1.128,
					cacheRead: 0.0564,
					cacheWrite: 0.3525,
				},
				releaseDate: "2026-06-02",
				family: "qwen",
			},
			"qwen3.7-standard": {
				id: "qwen3.7-standard",
				name: "Qwen3.7 Standard",
				contextWindow: 991000,
				maxInputTokens: 991000,
				maxTokens: 64000,
				capabilities: [
					"tools",
					"reasoning",
					"structured_output",
					"temperature",
					"prompt-cache",
				],
				pricing: {
					input: 0.282,
					output: 1.128,
					cacheRead: 0.0564,
					cacheWrite: 0.3525,
				},
				releaseDate: "2026-06-02",
				family: "qwen",
			},
			"qwen3.7-mini": {
				id: "qwen3.7-mini",
				name: "Qwen3.7 Mini",
				contextWindow: 991000,
				maxInputTokens: 991000,
				maxTokens: 64000,
				capabilities: [
					"tools",
					"reasoning",
					"structured_output",
					"temperature",
					"prompt-cache",
				],
				pricing: {
					input: 0.282,
					output: 1.128,
					cacheRead: 0.0564,
					cacheWrite: 0.3525,
				},
				releaseDate: "2026-06-02",
				family: "qwen",
			},
			"qwen3.7-light": {
				id: "qwen3.7-light",
				name: "Qwen3.7 Light",
				contextWindow: 991000,
				maxInputTokens: 991000,
				maxTokens: 64000,
				capabilities: [
					"tools",
					"reasoning",
					"structured_output",
					"temperature",
					"prompt-cache",
				],
				pricing: {
					input: 0.282,
					output: 1.128,
					cacheRead: 0.0564,
					cacheWrite: 0.3525,
				},
				releaseDate: "2026-06-02",
				family: "qwen",
			},
			"qwen3.7-tiny": {
				id: "qwen3.7-tiny",
				name: "Qwen3.7 Tiny",
				contextWindow: 991000,
				maxInputTokens: 991000,
				maxTokens: 64000,
				capabilities: [
					"tools",
					"reasoning",
					"structured_output",
					"temperature",
					"prompt-cache",
				],
				pricing: {
					input: 0.282,
					output: 1.128,
					cacheRead: 0.0564,
					cacheWrite: 0.3525,
				},
				releaseDate: "2026-06-02",
				family: "qwen",
			},
			"qwen3.7-nano": {
				id: "qwen3.7-nano",
				name: "Qwen3.7 Nano",
				contextWindow: 991000,
				maxInputTokens: 991000,
				maxTokens: 64000,
				capabilities: [
					"tools",
					"reasoning",
					"structured_output",
					"temperature",
					"prompt-cache",
				],
				pricing: {
					input: 0.282,
					output: 1.128,
					cacheRead: 0.0564,
					cacheWrite: 0.3525,
				},
				releaseDate: "2026-06-02",
				family: "qwen",
			},
			"glm-5.1": {
				id: "glm-5.1",
				name: "GLM-5.1",
				contextWindow: 1000000,
				maxInputTokens: 1000000,
				maxTokens: 128000,
				capabilities: [
					"tools",
					"reasoning",
					"structured_output",
					"temperature",
					"prompt-cache",
				],
				pricing: {
					input: 1.1268,
					output: 3.9438,
					cacheRead: 0.2817,
					cacheWrite: 0,
				},
				releaseDate: "2026-03-16",
				family: "glm",
			},
			"glm-4.7": {
				id: "glm-4.7",
				name: "GLM-4.7",
				contextWindow: 204800,
				maxInputTokens: 204800,
				maxTokens: 131072,
				capabilities: ["tools", "reasoning", "temperature"],
				pricing: {
					input: 0,
					output: 0,
					cacheRead: 0,
					cacheWrite: 0,
				},
				releaseDate: "2025-12-22",
				family: "glm",
			},
			"glm-4.5-air": {
				id: "glm-4.5-air",
				name: "GLM-4.5-Air",
				contextWindow: 131072,
				maxInputTokens: 131072,
				maxTokens: 98304,
				capabilities: ["tools", "reasoning", "temperature"],
				pricing: {
					input: 0,
					output: 0,
					cacheRead: 0,
					cacheWrite: 0,
				},
				releaseDate: "2025-07-28",
				family: "glm-air",
			},
		},
	},
};